//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOC_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        public long PRODUCT_ID { get; set; }
        public string PRODUCT_MODEL { get; set; }
        public Nullable<int> PRODUCT_TYPE_ID { get; set; }
        public string PRODUCT_DESC { get; set; }
        public Nullable<long> IMAGE_SRC_GROUP_ID { get; set; }
        public Nullable<int> IS_ON_MARKET { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> PRICE { get; set; }
        public Nullable<decimal> VAT { get; set; }
        public Nullable<int> SUPPLY_ID { get; set; }
        public Nullable<int> FROM_STOCK_ID { get; set; }
        public Nullable<int> TOTAL_QTY { get; set; }
        public Nullable<int> SOLD_QTY { get; set; }
        public Nullable<int> CURRENT_OWNER { get; set; }
        public Nullable<int> CURRENT_ITEM_ID { get; set; }
        public Nullable<int> CURRENT_ITEM_BY { get; set; }
        public Nullable<System.DateTime> START_DATE { get; set; }
        public Nullable<System.DateTime> END_DATE { get; set; }
        public string PRODUCT_STATUS { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<int> IS_DELETED { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
    }
}
