//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOC_DL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOCEntities : DbContext
    {
        public TOCEntities()
            : base("name=TOCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IMAGE> IMAGEs { get; set; }
        public virtual DbSet<LANGUAGE> LANGUAGEs { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCT_LANGUAGE> PRODUCT_LANGUAGEs { get; set; }
        public virtual DbSet<PRODUCT_TYPE> PRODUCT_TYPEs { get; set; }
        public virtual DbSet<SUPPLY> SUPPLies { get; set; }
        public virtual DbSet<USER> USERs { get; set; }
    }
}
