//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOC_DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USER_ID { get; set; }
        public string ACCOUNT_NO { get; set; }
        public string ACCOUNT_PASSWORD { get; set; }
        public Nullable<int> IS_ADMIN { get; set; }
        public string USER_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string FAX { get; set; }
        public string TEL { get; set; }
        public string LANGUAGE_TYPE { get; set; }
        public string SEX { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> CREATED_DATE { get; set; }
        public Nullable<int> CREATED_BY { get; set; }
        public Nullable<System.DateTime> LAST_UPDATED_DATE { get; set; }
        public Nullable<int> LAST_UPDATED_BY { get; set; }
        public Nullable<int> IS_DELETED { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public Nullable<int> DELETED_BY { get; set; }
    }
}
